name: me_recipe
description: A new Flutter project.
publish_to: 'none'

version: 1.0.2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2+1
  path_provider: ^2.0.9
  image_picker: ^0.8.5
  rxdart: ^0.27.3
  get_it: ^7.2.0
  google_fonts: ^2.3.2
  share_plus: ^4.0.4
  file_picker: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - default-recipe.png
